name: Terraform Deploy

on:
  push:
    branches: [main]

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Initialize Terraform
        uses: actions/github-script@v5
        with:
          script: |
            terraform init -backend-config="bucket=tf-personal-states"

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform changes
        run: terraform apply -input=false -auto-approve
